### PR TITLE
Get field by index

### PR DESCRIPTION
**Pull request by pfernie**

### CODE REVIEW

**Comment by bradfier** [comment]
Thanks so much for all these PRs!

This looks great, but since I merged your other two requests it doesn't apply cleanly anymore.
Can you rebase this onto master and possibly add a couple of tests?

**Comment by bradfier** [comment]
Apologies for Travis failing constantly, by the way. Since this crate needs the TIBCO distribution to build, and I didn't feel comfortable uploading their headers, the CI process pulls the dependencies from an external source.

This is kept in a Travis secret, so isn't available to third-party PRs, and even if it was it seems like Travis can't manage to `curl` the file half the time anyway.

**Comment by pfernie** [comment]
Rebased & added some simple tests. I figured that was the story w/ the Travis failures.

**Comment by bradfier** [comment]
Looks good, thanks!

Good catch on the `?` vs `.into()`

**Pull request merged**
